# Generated by Django 4.1.10 on 2024-07-28 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DhanClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('api_key', models.CharField(default='dhan', max_length=100)),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='AngelClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('api_key', models.CharField(default='angel', max_length=100)),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.appuser')),
            ],
        ),
    ]
