# Generated by Django 4.1.10 on 2024-08-03 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_angelclient_app_passcode_dhanclient_app_passcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhanclient',
            name='access_token',
        ),
    ]
