# Generated by Django 4.1.10 on 2024-08-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_dhanclient_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhanclient',
            name='access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
